// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ClassLibraryProject.Entities;

namespace RepositoryLibraryProject.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Apartment> Apartments { get; set; }

    public virtual DbSet<Building> Buildings { get; set; }

    public virtual DbSet<BuildingCompany> BuildingCompanies { get; set; }

    public virtual DbSet<BuildingImage> BuildingImages { get; set; }

    public virtual DbSet<BuildingStatusLog> BuildingStatusLogs { get; set; }

    public virtual DbSet<District> Districts { get; set; }

    public virtual DbSet<Floor> Floors { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<Request> Requests { get; set; }

    public virtual DbSet<RequestStatusLog> RequestStatusLogs { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<Street> Streets { get; set; }

    public virtual DbSet<Zipcode> Zipcode { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=devdemoserverbbdd.database.windows.net,1433;Initial Catalog=devdemobbdd;Persist Security Info=True;User ID=admsql;Password=P@ssw0rd;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>().ToTable("Address");
        modelBuilder.Entity<Apartment>().ToTable("Apartment");
        modelBuilder.Entity<Building>().ToTable("Building");
        modelBuilder.Entity<BuildingCompany>().ToTable("BuildingCompany");
        modelBuilder.Entity<BuildingImage>().ToTable("BuildingImage");
        modelBuilder.Entity<BuildingStatusLog>().ToTable("BuildingStatusLog");
        modelBuilder.Entity<District>().ToTable("District");
        modelBuilder.Entity<Floor>().ToTable("Floor");
        modelBuilder.Entity<Purchase>().ToTable("Purchase");
        modelBuilder.Entity<Request>().ToTable("Request");
        modelBuilder.Entity<RequestStatusLog>().ToTable("RequestStatusLog");
        modelBuilder.Entity<Status>().ToTable("Status");
        modelBuilder.Entity<Street>().ToTable("Street");

        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Address__3214EC0786A824B4");

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.ApartmentId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.BuildingId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.IsApartment)
                .IsRequired()
                .HasDefaultValueSql("((1))");
        });

        modelBuilder.Entity<Apartment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Apartmen__3214EC073CCFFB56");

            entity.ToTable(tb => tb.HasTrigger("TrgApartmentUpdateUpdatedAt"));

            entity.HasIndex(e => e.Code, "Apartment_Code").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Door)
                .IsRequired()
                .HasMaxLength(24)
                .IsUnicode(false);
            entity.Property(e => e.FloorId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);

            entity.HasOne(d => d.Floor).WithMany(p => p.Apartment)
                .HasForeignKey(d => d.FloorId)
                .HasConstraintName("FKApartment152603");
        });

        modelBuilder.Entity<Building>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Building__3214EC07B415885B");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("TrgBuildingStatusLogInsert");
                    tb.HasTrigger("TrgBuildingUpdateUpdatedAt");
                });

            entity.HasIndex(e => e.Code, "Building_Code").IsUnique();

            entity.HasIndex(e => e.Doorway, "Building_Doorway");

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.BuildingCompanyId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.DistrictId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Doorway)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false);
            entity.Property(e => e.EnergyCertificate)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Price)
                .HasDefaultValueSql("((0.00))")
                .HasColumnType("decimal(12, 2)");
            entity.Property(e => e.StatusId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.StreetId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.YearBuilt).HasDefaultValueSql("((1970))");

            entity.HasOne(d => d.BuildingCompany).WithMany(p => p.Building)
                .HasForeignKey(d => d.BuildingCompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding524337");

            entity.HasOne(d => d.District).WithMany(p => p.Building)
                .HasForeignKey(d => d.DistrictId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding875021");

            entity.HasOne(d => d.Status).WithMany(p => p.Building)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding279633");

            entity.HasOne(d => d.Street).WithMany(p => p.Building)
                .HasForeignKey(d => d.StreetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding420566");
        });

        modelBuilder.Entity<BuildingCompany>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Building__3214EC07590C204D");

            entity.ToTable(tb => tb.HasTrigger("TrgBuildingCompanyUpdateUpdatedAt"));

            entity.HasIndex(e => e.Cif, "BuildingCompany_Cif").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__Building__737584F6AD123444").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Cif)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Website)
                .HasMaxLength(1024)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BuildingImage>(entity =>
        {
            entity.HasKey(e => e.BuildingImageId).HasName("PK__Building__D744291255EE6541");

            entity.ToTable(tb => tb.HasTrigger("TrgBuildingImageUpdateUpdatedAt"));

            entity.HasIndex(e => e.FilePath, "UQ__Building__48D910BDD67E794E").IsUnique();

            entity.HasIndex(e => e.FileName, "UQ__Building__589E6EEC0815EC07").IsUnique();

            entity.Property(e => e.BuildingImageId)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.AltText)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.BuildingId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(1024)
                .IsUnicode(false);

            entity.HasOne(d => d.Building).WithMany(p => p.BuildingImage)
                .HasForeignKey(d => d.BuildingId)
                .HasConstraintName("FKBuildingIm593721");
        });

        modelBuilder.Entity<BuildingStatusLog>(entity =>
        {
            entity.HasKey(e => new { e.BuildingId, e.StatusId, e.CreatedAt }).HasName("PK__Building__138872FF04D62561");

            entity.Property(e => e.BuildingId)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.StatusId)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Building).WithMany(p => p.BuildingStatusLog)
                .HasForeignKey(d => d.BuildingId)
                .HasConstraintName("FKBuildingSt501021");

            entity.HasOne(d => d.Status).WithMany(p => p.BuildingStatusLog)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuildingSt885424");
        });

        modelBuilder.Entity<District>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__District__3214EC0732330B92");

            entity.ToTable(tb => tb.HasTrigger("TrgDistrictUpdateUpdatedAt"));

            entity.HasIndex(e => e.Name, "UQ__District__737584F657C378C6").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(24)
                .IsUnicode(false);

            entity.HasMany(d => d.Street).WithMany(p => p.District)
                .UsingEntity<Dictionary<string, object>>(
                    "DistrictStreet",
                    r => r.HasOne<Street>().WithMany()
                        .HasForeignKey("StreetId")
                        .HasConstraintName("FKDistrictSt200593"),
                    l => l.HasOne<District>().WithMany()
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("FKDistrictSt746137"),
                    j =>
                    {
                        j.HasKey("DistrictId", "StreetId").HasName("PK__District__33DAAA75642CE083");
                        j.IndexerProperty<string>("DistrictId")
                            .HasMaxLength(36)
                            .IsUnicode(false);
                        j.IndexerProperty<string>("StreetId")
                            .HasMaxLength(36)
                            .IsUnicode(false);
                    });
            entity.HasMany(d => d.Zipcode).WithMany(p => p.District)
    .UsingEntity<Dictionary<string, object>>(
        "DistrictZipcode",
        r => r.HasOne<Zipcode>().WithMany()
            .HasForeignKey("ZipcodeId")
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DistrictZipcode_Zipcode"),
        l => l.HasOne<District>().WithMany()
            .HasForeignKey("DistrictId")
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DistrictZipcode_District"),
        j =>
        {
            j.HasKey("DistrictId", "ZipcodeId");
            j.IndexerProperty<string>("DistrictId")
                .HasMaxLength(36)
                .IsUnicode(false);
            j.IndexerProperty<string>("ZipcodeId")
                .HasMaxLength(36)
                .IsUnicode(false);
        });
        });

        modelBuilder.Entity<Floor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Floor__3214EC07176607C0");

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.BuildingId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.HasLift)
                .IsRequired()
                .HasDefaultValueSql("((1))");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.Building).WithMany(p => p.Floor)
                .HasForeignKey(d => d.BuildingId)
                .HasConstraintName("FKFloor82292");
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Purchase__3214EC07ADEAF173");

            entity.ToTable(tb => tb.HasTrigger("TrgPurchaseUpdateUpdatedAt"));

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Amount)
                .HasDefaultValueSql("((0.00))")
                .HasColumnType("decimal(12, 2)");
            entity.Property(e => e.BuildingCompanyId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.BuildingId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.RequestId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);

            entity.HasOne(d => d.BuildingCompany).WithMany(p => p.Purchase)
                .HasForeignKey(d => d.BuildingCompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKPurchase526429");

            entity.HasOne(d => d.Building).WithMany(p => p.Purchase)
                .HasForeignKey(d => d.BuildingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKPurchase78453");

            entity.HasOne(d => d.Request).WithMany(p => p.Purchase)
                .HasForeignKey(d => d.RequestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKPurchase717750");
        });

        modelBuilder.Entity<Request>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Request__3214EC07D31EE00C");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("TrgRequestStatusLogInsert");
                    tb.HasTrigger("TrgRequestUpdateUpdatedAt");
                });

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.BuildingId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.StatusId)
                .IsRequired()
                .HasMaxLength(36)
                .IsUnicode(false);

            entity.HasOne(d => d.Building).WithMany(p => p.Request)
                .HasForeignKey(d => d.BuildingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKRequest514507");

            entity.HasOne(d => d.Status).WithMany(p => p.Request)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKRequest898910");
        });

        modelBuilder.Entity<RequestStatusLog>(entity =>
        {
            entity.HasKey(e => new { e.RequestId, e.StatusId, e.CreatedAt }).HasName("PK__RequestS__7443EE41D8C7BA45");

            entity.Property(e => e.RequestId)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.StatusId)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Request).WithMany(p => p.RequestStatusLog)
                .HasForeignKey(d => d.RequestId)
                .HasConstraintName("FKRequestSta565383");

            entity.HasOne(d => d.Status).WithMany(p => p.RequestStatusLog)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKRequestSta994406");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Status__3214EC07721A4E7C");

            entity.ToTable(tb => tb.HasTrigger("TrgStatusUpdateUpdatedAt"));

            entity.HasIndex(e => e.Name, "UQ__Status__737584F6BD329A59").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(48)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Street>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Street__3214EC07083EFE1A");

            entity.ToTable(tb => tb.HasTrigger("TrgStreetUpdateUpdatedAt"));


            entity.HasIndex(e => e.Code, "Street_Code").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(24)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Zipcode>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Zipcode__3214EC07B3F7E0D6");

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}