// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ClassLibraryProject.Entities;

namespace RepositoryLibraryProject.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Address { get; set; }

    public virtual DbSet<Apartment> Apartment { get; set; }

    public virtual DbSet<Building> Building { get; set; }

    public virtual DbSet<BuildingCompany> BuildingCompany { get; set; }

    public virtual DbSet<BuildingImage> BuildingImage { get; set; }

    public virtual DbSet<BuildingStatusLog> BuildingStatusLog { get; set; }

    public virtual DbSet<District> District { get; set; }

    public virtual DbSet<Floor> Floor { get; set; }

    public virtual DbSet<Purchase> Purchase { get; set; }

    public virtual DbSet<Request> Request { get; set; }

    public virtual DbSet<RequestStatusLog> RequestStatusLog { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<Street> Street { get; set; }

    public virtual DbSet<Zipcode> Zipcode { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=devdemoserverbbdd.database.windows.net,1433;Initial Catalog=devdemobbdd;Persist Security Info=True;User ID=admsql;Password=P@ssw0rd;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07A798E539");

            entity.Property(e => e.IsApartment).HasDefaultValueSql("((1))");

            entity.HasOne(d => d.Apartment).WithMany(p => p.Address).HasConstraintName("FKAddress937616");

            entity.HasOne(d => d.Building).WithMany(p => p.Address)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKAddress69853");

            entity.HasOne(d => d.Zipcode).WithMany(p => p.Address)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKAddress66912");
        });

        modelBuilder.Entity<Apartment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Apartmen__3214EC072BB504EA");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("TrgApartmentDeleteBuildingCount");
                    tb.HasTrigger("TrgApartmentInsertBuildingCount");
                    tb.HasTrigger("TrgApartmentUpdateUpdatedAt");
                });

            entity.Property(e => e.Area)
                .HasPrecision(18, 2);

            entity.HasOne(d => d.Floor).WithMany(p => p.Apartment).HasConstraintName("FKApartment152603");
        });

        modelBuilder.Entity<Building>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07FB8872D3");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("TrgBuildingDeleteDistrictCount");
                    tb.HasTrigger("TrgBuildingInsertDistrictCount");
                    tb.HasTrigger("TrgBuildingStatusLogInsert");
                    tb.HasTrigger("TrgBuildingUpdateUpdatedAt");
                });

            entity.Property(e => e.EnergyCertificate).IsFixedLength();
            entity.Property(e => e.Price)
                .HasPrecision(18, 2)
                .HasDefaultValueSql("((0.00))");
            entity.Property(e => e.YearBuilt).HasDefaultValueSql("((1970))");

            entity.HasOne(d => d.BuildingCompany).WithMany(p => p.Building)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding524337");

            entity.HasOne(d => d.District).WithMany(p => p.Building)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding875021");

            entity.HasOne(d => d.Status).WithMany(p => p.Building)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding279633");

            entity.HasOne(d => d.Street).WithMany(p => p.Building)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuilding420566");
        });

        modelBuilder.Entity<BuildingCompany>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Building__3214EC0700C9B9F4");

            entity.ToTable(tb => tb.HasTrigger("TrgBuildingCompanyUpdateUpdatedAt"));
        });

        modelBuilder.Entity<BuildingImage>(entity =>
        {
            entity.HasKey(e => e.BuildingImageId).HasName("PK__Building__D7442912C95376C0");

            entity.ToTable(tb => tb.HasTrigger("TrgBuildingImageUpdateUpdatedAt"));

            // Configuración para almacenamiento de imágenes en varbinary(max)
            entity.Property(e => e.RowGuid)
                .HasDefaultValueSql("NEWSEQUENTIALID()");

            entity.Property(e => e.ImageData)
                .HasColumnType("varbinary(max)")
                .IsRequired(false);

            entity.HasOne(d => d.Building).WithMany(p => p.BuildingImage).HasConstraintName("FKBuildingIm593721");
        });

        modelBuilder.Entity<BuildingStatusLog>(entity =>
        {
            entity.HasKey(e => new { e.BuildingId, e.StatusId, e.CreatedAt }).HasName("PK__Building__138872FF6FE64B89");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Building).WithMany(p => p.BuildingStatusLog).HasConstraintName("FKBuildingSt501021");

            entity.HasOne(d => d.Status).WithMany(p => p.BuildingStatusLog)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBuildingSt885424");
        });

        modelBuilder.Entity<District>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC078E1215D5");

            entity.ToTable(tb => tb.HasTrigger("TrgDistrictUpdateUpdatedAt"));

            entity.HasMany(d => d.Street).WithMany(p => p.District)
                .UsingEntity<Dictionary<string, object>>(
                    "DistrictStreet",
                    r => r.HasOne<Street>().WithMany()
                        .HasForeignKey("StreetId")
                        .HasConstraintName("FKDistrictSt200593"),
                    l => l.HasOne<District>().WithMany()
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("FKDistrictSt746137"),
                    j =>
                    {
                        j.HasKey("DistrictId", "StreetId").HasName("PK__District__33DAAA75F47B7E26");
                        j.IndexerProperty<string>("DistrictId")
                            .HasMaxLength(36)
                            .IsUnicode(false);
                        j.IndexerProperty<string>("StreetId")
                            .HasMaxLength(36)
                            .IsUnicode(false);
                    });

            entity.HasMany(d => d.Zipcode).WithMany(p => p.District)
                .UsingEntity<Dictionary<string, object>>(
                    "DistrictZipcode",
                    r => r.HasOne<Zipcode>().WithMany()
                        .HasForeignKey("ZipcodeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_DistrictZipcode_Zipcode"),
                    l => l.HasOne<District>().WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_DistrictZipcode_District"),
                    j =>
                    {
                        j.HasKey("DistrictId", "ZipcodeId");
                        j.IndexerProperty<string>("DistrictId")
                            .HasMaxLength(36)
                            .IsUnicode(false);
                        j.IndexerProperty<string>("ZipcodeId")
                            .HasMaxLength(36)
                            .IsUnicode(false);
                    });
        });

        modelBuilder.Entity<Floor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC077FD3A026");

            entity.HasOne(d => d.Building).WithMany(p => p.Floor).HasConstraintName("FKFloor82292");
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Purchase__3214EC079EECDF3F");

            entity.ToTable(tb => tb.HasTrigger("TrgPurchaseUpdateUpdatedAt"));
            entity.Property(e => e.Amount)
                .HasPrecision(18, 2)
                .HasDefaultValueSql("((0.00))");

            entity.HasOne(d => d.BuildingCompany).WithMany(p => p.Purchase)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKPurchase526429");

            entity.HasOne(d => d.Building).WithMany(p => p.Purchase)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKPurchase78453");

            entity.HasOne(d => d.Request).WithMany(p => p.Purchase)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKPurchase717750");
        });

        modelBuilder.Entity<Request>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Request__3214EC07927A47BE");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("TrgRequestStatusLogInsert");
                    tb.HasTrigger("TrgRequestUpdateUpdatedAt");
                });
                
            entity.Property(e => e.Price)
                .HasPrecision(18, 2);

            entity.HasOne(d => d.Building).WithMany(p => p.Request)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKRequest514507");

            entity.HasOne(d => d.Status).WithMany(p => p.Request)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKRequest898910");
        });

        modelBuilder.Entity<RequestStatusLog>(entity =>
        {
            entity.HasKey(e => new { e.RequestId, e.StatusId, e.CreatedAt }).HasName("PK__RequestS__7443EE417A538CCF");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Request).WithMany(p => p.RequestStatusLog).HasConstraintName("FKRequestSta565383");

            entity.HasOne(d => d.Status).WithMany(p => p.RequestStatusLog)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKRequestSta994406");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Status__3214EC075368BE62");

            entity.ToTable(tb => tb.HasTrigger("TrgStatusUpdateUpdatedAt"));
        });

        modelBuilder.Entity<Street>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Street__3214EC07C26C5B86");

            entity.ToTable(tb => tb.HasTrigger("TrgStreetUpdateUpdatedAt"));
        });

        modelBuilder.Entity<Zipcode>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Zipcode__3214EC07B3F7E0D6");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}